### PR TITLE
PR-MSH-TRANS

### LINKED ISSUE #36: Transactions
Core CURD Implementation.

- APIs
- Services
- Lower level classes
- Sps
- Develop testcases
- 
Note: must perform smoke testing before creating PR

### LINKED ISSUE #43: DBRepository GetAll Issue
**Describe the bug**
When string is unable to deserialize into DO objects. Exception is raising. 

**To Reproduce**
1. Go to SQL
2. Remove all data from the table.
3. Go to Swagger 
4. Open GetAll API
5. Run the API
6. See an error

**Expected behavior**
This should be returning null data.

### PR DESCRIPTION
**Pull request by MariamShaikh**
#36 ready to go!

### CODE REVIEW

File: database/storeprocds/spDeleteTransaction.sql [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+   WHERE SPECIFIC_SCHEMA = N'dbo'
+     AND SPECIFIC_NAME = N'spDeleteTransaction' 
+)
+   DROP PROCEDURE dbo.spDeleteTransaction
+GO
+
+CREATE PROCEDURE dbo.spDeleteTransaction
+	@RecId bigint
+AS
+	DELETE FROM USERSTATUS
```
Comment (maazk9119) [inline database/storeprocds/spDeleteTransaction.sql]: Seems weird, spDeleteTransaction is deleting data from UserStatus. Can you fix it?

File: src/Rakaposhi.Core/Rakaposhi.API.Core/Controllers/TransController.cs [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+
+        [HttpPost]
+        public ActionResult Create([FromBody] Trans trans)
+        {
+            try
+            {
+                _transService.Add(trans);
+
+                return Created("Get", trans);
+
```
Comment (maazk9119) [inline src/Rakaposhi.Core/Rakaposhi.API.Core/Controllers/TransController.cs:26]: Please remove unnecessary space.

File: src/Rakaposhi.Core/Rakaposhi.API.Core/Controllers/TransController.cs [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+            }
+        }
+
+        [HttpGet]
+        public ActionResult GetAll()
+        {
+            try
+            {
+                var userStatusList = _transService.GetAll();
+                return Ok(userStatusList);
```
Comment (maazk9119) [inline src/Rakaposhi.Core/Rakaposhi.API.Core/Controllers/TransController.cs:92]: Please add one line space before returning.

File: src/Rakaposhi.Core/Rakaposhi.Business.Core/BaseRepository/IRepositoryFactory.cs [hunk 4]
```diff
@@ -4,5 +4,7 @@ public interface IRepositoryFactory
     {
         public IUserRoleRepository UserRoleRepository { get; }
         public IUserStatusRepository UserStatusRepository { get; }
+
```
Comment (maazk9119) [inline src/Rakaposhi.Core/Rakaposhi.Business.Core/BaseRepository/IRepositoryFactory.cs]: Please remove unnecessary linespace

File: src/Rakaposhi.Core/Rakaposhi.Business.Core/DBRepository/TransRepository.cs [hunk 5]
```diff
@@ -0,0 +1,86 @@
...
+        }
+
+        private struct Params
+        {
+            public const string RECID = "RecId";
+            public const string USERID = "UserId";
+            public const string TRANSTYPE = "TransType";
+            public const string AMOUNT = "Amount";
+            public const string DATE = "Date";
+
```
Comment (maazk9119) [inline src/Rakaposhi.Core/Rakaposhi.Business.Core/DBRepository/TransRepository.cs]: Please remove unnecessary linespace

File: src/Rakaposhi.Core/Rakaposhi.Business.Core/Services/TransService.cs [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+
+        public void Add(Trans trans)
+        {
+            if(trans.RecId == null)
+            {
+                throw new ServiceException(ErrorCode.ADDERROR);
+            }
+
+            _factory.TransRepository.Add(trans);
+
```
Comment (maazk9119) [inline src/Rakaposhi.Core/Rakaposhi.Business.Core/Services/TransService.cs]: Please remove unnecessary linespace

**Review by maazk9119 — APPROVED** [review]
Good to go
